
version: '3.8'
services:
  fiquelivre-postgresql:
    image: bitnami/postgresql:latest
    container_name: findYourDuo-postgresql
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    volumes:
      - postgresql-data:/bitnami/postgresql
    networks:
      - containers-network

volumes:
  postgresql-data:

networks:
  containers-network:
    driver: bridge
